apiVersion: v1
kind: Pod
metadata:
 name: kubernetes-dapi-vol-eg
 labels:
  zone: us-est-coast
  cluster: t-c1
  rack: r-22
 annotations:
  build: two
  builder: john-doe
spec:
 containers:
 - name: client-container
   image: k8s.gcr.io/busybox
   command: ["sh","-c"]
   args:
   - while true;do
      if [[ -e /etc/podinfo/labels ]]; then
       echo -en '\n\n\'; cat /etc/podinfo/labels; fi;
      if [[ -e /etc/podinfo/annotations; then
       echo -en '\n\n\'; cat /etx/podinfo/annotations; fi;
      sleep 5;
     done;
   volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: false
 volumes:
 - name: podinfo
   downwardAPI:
    items:
     - path: "labels"
       fieldRef:
         fieldPath: metadata.labels
     - path: "annotations"
       fieldRef:
         fieldPath: metadata.annotations

