apiVersion: v1
kind: Pod
metadata:
 labels:
  name: toleration
spec:
 containers:
 - name: nginx
   image: nginx
 tolerations:
 - key: "dev"
   operator: "Equal"
   value: "env"
   effect: "NoSchedule"
